name: Trigger auto deployment for cmgpscontainerhost

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cmgpscontainerhost-AutoDeployTrigger-9205f185-1713-4d48-a989-2cdf2ad81444.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca1e6212d080acr.azurecr.io
          username: ${{ secrets.CMGPSCONTAINERHOST_REGISTRY_USERNAME }}
          password: ${{ secrets.CMGPSCONTAINERHOST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca1e6212d080acr.azurecr.io/cmgpscontainerhost:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CMGPSCONTAINERHOST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cmgpscontainerhost -g cmgpsContainerApps --server ca1e6212d080acr.azurecr.io --username  ${{ secrets.CMGPSCONTAINERHOST_REGISTRY_USERNAME }} --password ${{ secrets.CMGPSCONTAINERHOST_REGISTRY_PASSWORD }}
            az containerapp update -n cmgpscontainerhost -g cmgpsContainerApps --image ca1e6212d080acr.azurecr.io/cmgpscontainerhost:${{ github.sha }}
